pip_install_packages:
  - docker

pip_package: python3-pip

app_name: xsolla-test
app_port: 8000
app_image: feycot/xsolla-summer-school-backend-2021-prod

datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: devops_lvl3_project_status
        url: http://localhost:8000
        timeout: 5
        method: GET
