stages:
  - build
  - deploy

build:
  stage: build
  image: docker/compose:debian-1.29.1
  services:
    - docker:dind
  variables:
    COMPOSE_PROJECT_NAME: xsolla-summer-school-backend-2021-ci
    COMPOSE_FILE: docker-compose.yml
  before_script:
    - apt update && apt install make
  script:
    - make ci

deploy_heroku:
  stage: deploy
  dependencies:
    - build
  only:
    - master
  when: on_success
  before_script:
    - cat $HEROKU_AUTH_DATA > ~/.netrc
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - make deploy-heroku

deploy_prod:
  stage: deploy
  dependencies:
    - build
  when: manual
  only:
    - master
  script:
    - echo "RUN DEPLOY"
