stages:
  # - build
  - deploy

# build:
#   stage: build
#   image: docker/compose:debian-1.29.1
#   services:
#     - docker:dind
#   variables:
#     COMPOSE_PROJECT_NAME: xsolla-summer-school-backend-2021-ci
#     COMPOSE_FILE: docker-compose.yml
#   script:
#     - docker-compose  build
#     - docker-compose run app make setup
#     - docker-compose up --abort-on-container-exit

deploy_heroku:
  image: ubuntu:20.04
  stage: deploy
  # dependencies:
  #   - build
  when: manual
  only:
    - master
  before_script:
    - apt install curl
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - make deploy

deploy_prod:
  stage: deploy
  # dependencies:
  #   - build
  when: manual
  only:
    - master
  script:
    - echo "RUN DEPLOY"
