FROM feycot/xsolla-summer-school-backend-2021-base:latest

COPY composer.json .
COPY composer.lock .
COPY . .

RUN composer install --no-dev --optimize-autoloader

ENV LOG_CHANNEL=errorlog

CMD make start
